version: '3.8'

services:
  prod:
    image: football-numbers-prod:latest
    container_name: prod-env_prod_1
    build:
      context: ${PROJECT_ROOT:-.}
      dockerfile: ./prod-env/Containerfile
    ports:
      - "3030:3000"
    hostname: ${PROD_HOSTNAME}
    environment:
      - NODE_ENV=production
    networks:
      - prod_network
    restart: unless-stopped

networks:
  prod_network:
    driver: bridge
