version: '3.8'

services:
  dev:
    image: football-numbers-dev:latest
    build:
      context: .
      dockerfile: Containerfile
    container_name: football_numbers_dev
    ports:
      - "3000:3000"
    volumes:
      - ${PROJECT_ROOT:-.}:/workspace:z
    working_dir: /workspace
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=development
    networks:
      - dev_network

networks:
  dev_network:
    driver: bridge
