version: '3.8'

services:
  dev:
    image: football-numbers-dev:latest
    container_name: dev-env_dev_1
    build:
      context: .
      dockerfile: Containerfile
    ports:
      - "3000:3000"
    volumes:
      - ${PROJECT_ROOT:-.}:/workspace:z
      - ${DATA_PROJECT_ROOT:-.}:/data:ro,z
    working_dir: /workspace
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=development
    hostname: ${DEV_HOSTNAME}
    networks:
      - dev_network

networks:
  dev_network:
    driver: bridge
